<?php

use Illuminate\Validation;
use Illuminate\Filesystem;
use Illuminate\Translation;
use Dotenv\Dotenv;

require_once('../vendor/autoload.php');
require_once('validationMessages.php');
require_once('validationCustomAttributes.php');

/**
 * Load Dotenv
 */
$dotenv = Dotenv::create(__DIR__.'../../');
$dotenv->load();

/**
 * Create and declare validation factory
 */
$filesystem = new Filesystem\Filesystem();
$fileLoader = new Translation\FileLoader($filesystem, '');
$translator = new Translation\Translator($fileLoader, 'es');
$validationFactory = new Validation\Factory($translator);

/**
 * Create and declare mailer
 */
switch ($_ENV['MAIL_DRIVER']) {
    case 'smtp':
        $transport = (new Swift_SmtpTransport($_ENV['MAIL_HOST'], $_ENV['MAIL_PORT']))
          ->setUsername($_ENV['MAIL_USERNAME']) // generated by Mailtrap
          ->setPassword($_ENV['MAIL_PASSWORD']) // generated by Mailtrap
        ;
        break;

    default:
        $transport = new Swift_SendmailTransport();
        break;
}

$mailer = new Swift_Mailer($transport);

function url() {
  $result = parse_url($_SERVER['PHP_SELF']);
  return $result['scheme']."://".$result['host'];
}

/**
 * HTTP Method validation
 * @param string $method
 */
function validateMethod($method = 'post')
{
    if (strtolower($_SERVER['REQUEST_METHOD']) !== $method) {
        header($_SERVER["SERVER_PROTOCOL"]." 405 Method Not Allowed", true, 405);
        respondWithErrorMessage('405 Method Not Allowed', 405);
        exit();
    }

    return true;
}

/**
 * Recaptcha validation
 * @param string $inputName
 */
function validateRecaptcha($inputName)
{
    if (empty($_ENV['RECAPTCHA_SECRET'])) {
        return  true;
    }

    if (!isset($_POST[$inputName])) {
        respondWithErrorMessage('Por favor verifica en el formulario que no eres un robot', 400);
    }

    $recaptcha_response = json_decode(file_get_contents('https://www.google.com/recaptcha/api/siteverify?secret='.$_ENV['RECAPTCHA_SECRET'].'&response='.$_POST[$inputName].'&remoteip='.$_SERVER['REMOTE_ADDR']), true);

    if ($recaptcha_response['success'] == false) {
       respondWithErrorMessage('No fue posible verificar que no eres un robot', 400);
    }
}

/**
 * Validate all necesary env variables are set
 */
function validateMailConfig()
{
    if ($_ENV['MAIL_DRIVER'] == 'mail') {
        return true;
    }

    if (
        $_ENV['MAIL_DRIVER'] == 'smtp' &&
        !empty($_ENV['MAIL_HOST']) &&
        !empty($_ENV['MAIL_PORT']) &&
        !empty($_ENV['MAIL_USERNAME']) &&
        !empty($_ENV['MAIL_PASSWORD']) &&
        !empty($_ENV['MAIL_TO'])
    ) {
        return true;
    }

    return false;
}

/**
 * Data and input sanitizing
 * @param array $data
 */
function cleanInput($data)
{
    foreach ($data as $key => $value) {
        $value = trim($value);
        $value = filter_var($value, FILTER_SANITIZE_STRING);
        $value = strip_tags($value);

        $data[$key] = $value;
    }

    return $data;
}

/**
 * JSON response with error message
 * @param string $message
 * @param integer $code
 */
function respondWithErrorMessage($message, $code = 400)
{
    $response = [
        'status' => 'error',
        'message' => $message,
        'errors' => [],
    ];

    respond($response, $code);
    exit();
}

/**
 * JSON generic response
 * @param array $data
 * @param integer $code
 * @param string $contentType
 */
function respond($data = [], $code = 200, $contentType = 'Content-type:application/json;charset=utf-8')
{
    header($contentType);
    http_response_code($code);
    echo json_encode($data);
    exit();
}
